# Git repository containing the Helm charts
repoURL: "https://github.com/pizour/infra-agentic-incident-triage.git"

# Target revision (branch, tag, or commit hash)
targetRevision: "main"

# Definitions for all applications to be deployed via GitOps
applications:
  - name: monitoring
    path: services/monitoring
    namespace: monitoring
  - name: netbox
    path: services/netbox
    namespace: netbox
  - name: zammad
    path: services/zammad
    namespace: zammad
  - name: linux-mcp-server
    path: services/linux-mcp-server
    namespace: ai-agent
  - name: netbox-mcp-server
    path: services/netbox-mcp-server
    namespace: ai-agent
  - name: github-mcp-server
    path: services/github-mcp-server
    namespace: ai-agent
  - name: router-agent
    path: services/router-agent
    namespace: ai-agent
  - name: ai-orchestrator
    path: services/ai-orchestrator
    namespace: ai-agent
  - name: langfuse
    path: services/langfuse
    namespace: ai-agent
