apiVersion: v1
kind: Service
metadata:
  name: {{ include "langfuse.fullname" . }}
  labels:
    app.kubernetes.io/name: langfuse
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: langfuse
