apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbox-mcp-server.fullname" . }}
  labels: {{- include "netbox-mcp-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8002
      protocol: TCP
      name: http
  selector: {{- include "netbox-mcp-server.selectorLabels" . | nindent 4 }}
