apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "router-agent.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
