apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
