apiVersion: v2
name: langfuse-wrapper
description: Langfuse v3 - wrapper chart using official langfuse-k8s
type: application
version: 3.0.0
appVersion: "3"

dependencies:
  - name: langfuse
    version: "1.x.x"
    repository: "https://langfuse.github.io/langfuse-k8s"
