replicaCount: 1

image:
  registry: europe-west4-docker.pkg.dev
  project: ai-incident-triage
  repository: gke-artifacts-dev
  name: ai-orchestrator
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8009

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://monitoring-phoenix.monitoring.svc.cluster.local:6006/v1/traces"
  ROUTER_API: "http://router-agent.ai-agent.svc.cluster.local:8010/run"
  GENERIC_AGENT_IMAGE: "europe-west4-docker.pkg.dev/ai-incident-triage/gke-artifacts-dev/ai-agent:latest"
  NAMESPACE: "ai-agent"
  GOOGLE_CLOUD_PROJECT: "ai-incident-triage"
  GOOGLE_CLOUD_LOCATION: "europe-west4"
  AGENT_SERVICE_ACCOUNT: "router-agent"
  LANGFUSE_HOST: "http://langfuse-web.ai-agent.svc.cluster.local:3000"
  GOOGLE_APPLICATION_CREDENTIALS: "/etc/gcp/sa-key.json"

# Secrets injected as env vars from K8s Secret
secrets:
  APP_API_KEY: ""
  LANGFUSE_PUBLIC_KEY: ""
  LANGFUSE_SECRET_KEY: ""
  GH_OAUTH_APP_ID: ""
  GH_OAUTH_CLIENT_ID: ""
  GH_OAUTH_CLIENT_SECRET: ""
  GH_OAUTH_PRIVATE_KEY: ""
  GH_OAUTH_INSTALLATION_ID: ""
