replicaCount: 1

image:
  registry: europe-west4-docker.pkg.dev
  project: ai-incident-triage
  repository: gke-artifacts-dev
  name: linux-mcp-server
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8001

resources: {}

autoscaling:
  enabled: false

secrets:
  MCP_API_KEY: "" # Loaded via pipeline
  REMOTE_USER: "" # Loaded via pipeline
  REMOTE_PASS: "" # Loaded via pipeline
