models:
  - type: main
    engine: openai
    model: llama3.2:3b
    parameters:
      base_url: "http://ollama-stack-ollama.ollama.svc.cluster.local:11434/v1"
      api_key: "ollama"

rails:
  config:
    path: /app/monitoring/guardrails
