apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbox.fullname" . }}-secrets
type: Opaque
data:
  NETBOX_DB_PASS: {{ .Values.secrets.NETBOX_DB_PASS | b64enc | quote }}
  NETBOX_SECRET_KEY: {{ .Values.secrets.NETBOX_SECRET_KEY | b64enc | quote }}
  NETBOX_API_TOKEN: {{ .Values.secrets.NETBOX_API_TOKEN | b64enc | quote }}
  NETBOX_ADMIN_PASS: {{ .Values.secrets.NETBOX_ADMIN_PASS | b64enc | quote }}
