config:
  gcp:project: ai-incident-triage
  gcp:region: europe-west4
  gke-infra:environment: dev
  network:name: gke-network-dev
  network:subnet: gke-subnet-dev
  network:cidr: 10.0.0.0/20
  network:pods_cidr: 10.4.0.0/14
  network:services_cidr: 10.0.16.0/20
  gke:zone: europe-west4-a
  gke:cluster_name: gke-cluster-dev
  gke:version: "1.34"
  gke:enable_network_policy: "true"
  gke:enable_autoscaling: "true"
  gke:node_pool_name: default-pool-dev
  gke:machine_type: n2-standard-4
  gke:min_node_count: "1"
  gke:max_node_count: "1"
  gke:disk_size_gb: "100"
  gke:gpu_node_pool_name: l4-pool-dev
  gke:gpu_zone: europe-west4-a
  gke:gpu_machine_type: g4-standard-48
  gke:gpu_accelerator_type: nvidia-rtx-pro-6000
  gke:gpu_accelerator_count: "1"
  gke:gpu_spot: "true"
  gke:gpu_min_node_count: "1"
  gke:gpu_max_node_count: "1"
  gke:gpu_disk_size_gb: "100"
  argocd:chart_version: "7.7.16"
  argocd:chart_repo: https://argoproj.github.io/argo-helm
  argocd:namespace: argocd
encryptionsalt: v1:cz8ZEzlZPis=:v1:eRsjSjepHc1MW6Bx:OSrEUEvzMhKmaH0epUpXWZLax++xlg==
