apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zammad.fullname" . }}-elasticsearch
  labels:
    app.kubernetes.io/name: zammad-elasticsearch
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  serviceName: {{ include "zammad.fullname" . }}-elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zammad-elasticsearch
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zammad-elasticsearch
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
          imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.elasticsearch.persistence.storageClass }}
        storageClassName: {{ .Values.elasticsearch.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.elasticsearch.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zammad.fullname" . }}-elasticsearch
  labels:
    app.kubernetes.io/name: zammad-elasticsearch
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
      targetPort: 9200
      protocol: TCP
      name: elasticsearch
  selector:
    app.kubernetes.io/name: zammad-elasticsearch
    app.kubernetes.io/instance: {{ .Release.Name }}
