apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zammad.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: zammad
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  ZAMMAD_DB_PASS: {{ .Values.secrets.ZAMMAD_DB_PASS | b64enc | quote }}
  ZAMMAD_ADMIN_EMAIL: {{ .Values.secrets.ZAMMAD_ADMIN_EMAIL | b64enc | quote }}
  ZAMMAD_ADMIN_PASSWORD: {{ .Values.secrets.ZAMMAD_ADMIN_PASSWORD | b64enc | quote }}
  ZAMMAD_ADMIN_FIRSTNAME: {{ .Values.secrets.ZAMMAD_ADMIN_FIRSTNAME | b64enc | quote }}
  ZAMMAD_ADMIN_LASTNAME: {{ .Values.secrets.ZAMMAD_ADMIN_LASTNAME | b64enc | quote }}
