apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zammad.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: zammad
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  ZAMMAD_DB_PASS: {{ .Values.secrets.ZAMMAD_DB_PASS | b64enc | quote }}
