apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticket-agent.fullname" . }}
  labels: {{- include "ticket-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector: {{- include "ticket-agent.selectorLabels" . | nindent 4 }}
