fullnameOverride: "netbox"

db:
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
  user: netbox
  database: netbox
  service:
    port: 5432
  persistence:
    size: 20Gi
    storageClass: ""

redis:
  image:
    repository: redis
    tag: 7-alpine
    pullPolicy: IfNotPresent
  service:
    port: 6379

app:
  image:
    repository: netboxcommunity/netbox
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8080
  superuser:
    name: admin
    email: "admin@example.com"
  extraPy: |
    API_TOKEN_PEPPERS = {
        1: 'NetBoxLabsSeedPepper12345678901234567890123456789012',
    }
secrets:
  NETBOX_DB_PASS: "netboxpassword"
  NETBOX_SECRET_KEY: "super-secret-key-at-least-50-chars-long-1234567890123"
  NETBOX_API_TOKEN: "0123456789abcdef0123456789abcdef01234567"
  NETBOX_ADMIN_PASS: "admin"
